import { Game } from 'src/app/models/game';



export const GAMES: Game[] = [
    { id: 1, title: "Blood Rage", minPlayer: 2, maxPlayer: 5, description:"Life is Battle; Battle is Glory; Glory is ALL. In Blood Rage, each player controls their own Viking clan’s warriors, leader, and ship. Ragnarök has come, and it’s the end of the world! It’s the Vikings’ last chance to go down in a blaze of glory and secure their place in Valhalla at Odin’s side! For a Viking there are many pathways to glory. You can invade and pillage the land for its rewards, crush your opponents in epic battles, fulfill quests, increase your clan's stats, or even die gloriously either in battle or from Ragnarök, the ultimate inescapable doom.", imagePath:"https://cf.geekdo-images.com/imagepage/img/op_BYsCGVw_PftIoCa-OWucsUFc=/fit-in/900x600/filters:no_upscale()/pic2439223.jpg"},
    { id: 2, title: "Lost Cities", minPlayer: 2, maxPlayer: 2, description:"The object the game is to gain points by mounting profitable archaeological expeditions to the different sites represented by the 5 colors. On a player's turn they must always first play one card, either to an expedition or by discarding it to the appropriate discard pile, and then draw one card. There is a separate discard pile for each color and a player may draw the top card of any discard pile or the top card of the deck. Cards played to expeditions must be in ascending order but they need not be consecutive. ", imagePath:"https://cf.geekdo-images.com/imagepage/img/kNOK3IkwYIeoOQAeOMhOH9U7z88=/fit-in/900x600/filters:no_upscale()/pic2606107.jpg"},
    { id: 3, title: "Patch Work", minPlayer: 2, maxPlayer: 2, description:"In Patchwork, two players compete to build the most aesthetic (and high-scoring) patchwork quilt on a personal 9x9 game board. To start play, lay out all of the patches at random in a circle and place a marker directly clockwise of the 2-1 patch. Each player takes five buttons — the currency/points in the game — and someone is chosen as the start player." , imagePath:"https://cf.geekdo-images.com/imagepage/img/P-mb1HCtL_bAK0Knq_LR86Hxzdw=/fit-in/900x600/filters:no_upscale()/pic2270442.jpg"},
    { id: 4, title: "Cosmic Encounter", minPlayer: 3, maxPlayer: 6, description:"Build a galactic empire... In the depths of space, the alien races of the Cosmos vie with each other for control of the universe. Alliances form and shift from moment to moment, while cataclysmic battles send starships screaming into the warp. Players choose from dozens of alien races, each with its own unique power to further its efforts to build an empire that spans the galaxy.", imagePath:"https://cf.geekdo-images.com/imagepage/img/jAVGM9IeOy7dxdAr2ssJx8BbrGg=/fit-in/900x600/filters:no_upscale()/pic1521633.jpg"},
    { id: 5, title: "Captain Sonar", minPlayer: 6, maxPlayer: 8, description:"At the bottom of the ocean, no one will hear you scream! In Captain Sonar, you and your teammates control a state-of-the-art submarine and are trying to locate an enemy submarine in order to blow it out of the water before they can do the same to you. Every role is important, and the confrontation is merciless. Be organized and communicate because a captain is nothing without his crew: the Chief Mate, the Radio Operator, and the Engineer.", imagePath:"https://cf.geekdo-images.com/imagepage/img/eBQsy-K267ZgE_fNmxsbNDKUhng=/fit-in/900x600/filters:no_upscale()/pic3013621.png"},
    { id: 6, title: 'Codenames',  minPlayer: 2, maxPlayer: 10,  description:'a fun game', imagePath:"https://cf.geekdo-images.com/imagepage/img/BwJJTrofiaH0Muxuo5rv0VCmuCY=/fit-in/900x600/filters:no_upscale()/pic2582929.jpg" },
    { id: 7, title: 'Dead of Winter',  minPlayer: 3, maxPlayer: 5, description:'Dead of Winter: A Crossroads Game, the first game in this series, puts 2-5 players in a small, weakened colony of survivors in a world where most of humanity is either dead or diseased, flesh-craving monsters. Each player leads a faction of survivors with dozens of different characters in the game.', imagePath:"https://cf.geekdo-images.com/imagepage/img/IoC3kSvE7fHaZV868Mf_jbpx8r8=/fit-in/900x600/filters:no_upscale()/pic3016500.jpg" },
    { id: 8, title: 'Azul',  minPlayer: 2, maxPlayer: 4, description:'Azul is an abstract board game designed by Michael Kiesling and released by Plan B Games in 2017. Based on Portuguese tiles called azulejos, in Azul players collect sets of similarly colored tiles which they place on their player board', imagePath:"https://cf.geekdo-images.com/imagepage/img/mswTFqJsQ_omcKa_y1yNfFMJP6M=/fit-in/900x600/filters:no_upscale()/pic3718275.jpg" },
    { id: 9, title: 'Pandemic',  minPlayer: 2, maxPlayer: 4, description:'In Pandemic, several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand.', imagePath:"https://cf.geekdo-images.com/imagepage/img/3mRLkaz_shArWqExOXUS59cQowY=/fit-in/900x600/filters:no_upscale()/pic1534148.jpg" },
    { id: 10, title: 'Inis',  minPlayer: 2, maxPlayer: 7, description:'Inis is a game deeply rooted in Celtic history and lore in which players win by being elected King of the Island (Inis). ', imagePath:"https://cf.geekdo-images.com/imagepage/img/c6vFqiWZr3ix-2rMkUA0idcaOfk=/fit-in/900x600/filters:no_upscale()/pic3112623.jpg" },
    { id: 11, title: 'Smallworld',  minPlayer: 2, maxPlayer: 5, description:'In Small World, players vie for conquest and control of a world that is simply too small to accommodate them all. Designed by Philippe Keyaerts as a fantasy follow-up to his award-winning Vinci, Small World is inhabited by a zany cast of characters such as dwarves, wizards, amazons, giants, orcs, and even humans, who use their troops to occupy territory and conquer adjacent lands in order to push the other races off the face of the earth.', imagePath:"https://cf.geekdo-images.com/imagepage/img/voiO0qFy3gEcytkQX_-ueewX2_U=/fit-in/900x600/filters:no_upscale()/pic428828.jpg" },
    { id: 12, title: 'Mechs vs Minions',  minPlayer: 2, maxPlayer: 5, description:'Mechs vs. Minions is a cooperative tabletop campaign for 2-4 players. Set in the world of Runeterra, players take on the roles of four intrepid Yordles: Corki, Tristana, Heimerdinger, and Ziggs, who must join forces and pilot their newly-crafted mechs against an army of marauding minions. With modular boards, programmatic command lines, and a story-driven campaign, each mission will be unique, putting your teamwork, programming, and piloting skills to the test.', imagePath:"https://cf.geekdo-images.com/imagepage/img/jSCuD_9BFp6KFj1Fxor2-zV10A4=/fit-in/900x600/filters:no_upscale()/pic3184103.jpg" }, 
    { id: 13, title: 'Sagrada',  minPlayer: 2, maxPlayer: 3, description:'Draft dice and use the tools-of-the-trade in Sagrada to carefully construct your stained glass window masterpiece.  In more detail, each player builds a stained glass window by building up a grid of dice on their player board. Each board has some restrictions on which color or shade (value) of die can be placed there. Dice of the same shade or color may never be placed next to each other. Dice are drafted in player order, with the start player rotating each round, snaking back around after the last player drafts two dice. Scoring is variable per game based on achieving various patterns and varieties of placement...as well as bonus points for dark shades of a particular hidden goal color.', imagePath:"https://cf.geekdo-images.com/imagepage/img/dugmXVmeKi5YSaaJpyt_aFP80Yc=/fit-in/900x600/filters:no_upscale()/pic3525224.jpg" },
 
]

